import { EditorState } from '@codemirror/state';
import { EditorView } from '@codemirror/view';

import { type PolicyReference, type PolicyRegion, lineRegions, policyBlocks } from './policyBlocks';

// A generated file as the compiler writes it: the banner (lines 1-8) belongs to no block.
const POLICY = [
  '###############################################################################',
  '#',
  '# Turns a host into a web server.',
  '#',
  '# Generated by CFEngine Policy Builder from "Web".',
  '# Edits here are overwritten when the project is saved.',
  '#',
  '###############################################################################',
  '',
  'bundle agent web',
  '{',
  '  methods:',
  '    "install" usebundle => web_install;',
  '    "report" usebundle => web_report,',
  '      if => "web_ready";',
  '}',
  '',
  'bundle agent web_group',
  '{',
  '  reports:',
  '    "$(common:vars.port)";',
  '}'
].join('\n');

const region = (id: string, ranges: [number, number][], isGroup = false): PolicyRegion => ({
  id,
  ranges,
  isGroup,
  color: 'red',
  label: `${id} label`,
  type: `${id} type`
});

const install = region('install', [[13, 13]]);
const report = region('report', [
  [14, 15],
  [20, 21]
]);
const group = region('group', [[18, 22]], true);
const references: PolicyReference[] = [{ fileId: 'common', id: 'vars-block', name: 'common:vars.port' }];

describe('lineRegions', () => {
  it('maps each line to its block, and the banner to none', () => {
    const byLine = lineRegions([install, report]);
    for (let line = 1; line <= 12; line += 1) expect(byLine.get(line)).toBeUndefined();
    expect(byLine.get(13)).toBe(install);
    expect([14, 15, 20, 21].map(line => byLine.get(line))).toEqual([report, report, report, report]);
    expect(byLine.get(16)).toBeUndefined();
  });

  it('gives a block the lines it shares with its group, whatever the order', () => {
    const byLine = lineRegions([report, group]);
    expect([18, 19, 20, 21, 22].map(line => byLine.get(line)?.id)).toEqual(['group', 'group', 'report', 'report', 'group']);
  });
});

describe('policyBlocks', () => {
  let view: EditorView;
  const onSelect = vi.fn();
  const onFollow = vi.fn();

  beforeEach(() => {
    onSelect.mockReset();
    onFollow.mockReset();
    const extensions = policyBlocks([install, report, group], references, onSelect, onFollow);
    view = new EditorView({ state: EditorState.create({ doc: POLICY, extensions }), parent: document.body });
  });

  afterEach(() => view.destroy());

  // jsdom has no layout: point the click at a document position directly.
  const clickAt = (pos: number, target: Element = view.contentDOM) => {
    view.posAtCoords = () => pos;
    target.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  };
  const lineStart = (line: number) => view.state.doc.line(line).from;

  it('draws a bar per block line in the gutter, none beside the banner', () => {
    const bars = [...view.dom.querySelectorAll<HTMLElement>('.cm-block-gutter .cm-gutterElement')].map(element =>
      element.querySelector('.cm-block-bar')?.getAttribute('title')
    );
    expect(bars.filter(Boolean)).toEqual([
      'install label · install type',
      'report label · report type',
      'report label · report type',
      'group label · group type',
      'group label · group type',
      'report label · report type',
      'report label · report type',
      'group label · group type'
    ]);
  });

  it('shows a block’s type after each of its ranges’ first line, not a group’s', () => {
    expect([...view.dom.querySelectorAll('.cm-block-type')].map(tag => tag.textContent)).toEqual(['install type', 'report type', 'report type']);
  });

  it('selects the block clicked on', () => {
    clickAt(lineStart(15) + 4);
    expect(onSelect).toHaveBeenCalledWith('report');
    clickAt(lineStart(19));
    expect(onSelect).toHaveBeenLastCalledWith('group');
  });

  it('selects nothing on the banner', () => {
    clickAt(lineStart(3));
    expect(onSelect).not.toHaveBeenCalled();
  });

  it('follows a reference instead of selecting', () => {
    const link = view.dom.querySelector('[data-ref="common:vars.port"]');
    expect(link).not.toBeNull();
    clickAt(lineStart(21) + 6, link!);
    expect(onFollow).toHaveBeenCalledWith(references[0]);
    expect(onSelect).not.toHaveBeenCalled();
  });

  it('does not select while text is selected', () => {
    view.dispatch({ selection: { anchor: lineStart(13), head: lineStart(14) } });
    clickAt(lineStart(13));
    expect(onSelect).not.toHaveBeenCalled();
  });
});
