// CFEngine's built-in special variables (const.*, sys.*) — a static snapshot of
// stable identifiers reported by `cf-promises --show-vars` (CFEngine Core
// 3.28.0), not a live query: the packaged app can't assume CFEngine tooling is
// installed on the machine it runs on. Excludes per-host dynamic entries
// (e.g. sys.ipv4[en0], sys.mac_<address>) since those aren't stable names —
// their keys depend on the network interfaces of whatever host produced them.
// mon.* isn't included: those only populate once cf-monitord has run.
export interface SpecialVariable {
  description?: string;
  name: string;
}

export const specialVariables: SpecialVariable[] = [
  { name: 'const.at', description: 'Literal @ character' },
  { name: 'const.dirsep', description: 'Platform path separator (/ or \\)' },
  { name: 'const.dollar', description: 'Literal $ character' },
  { name: 'const.endl', description: 'Platform line ending' },
  { name: 'const.linesep', description: 'Platform line separator' },
  { name: 'const.n', description: 'Newline character' },
  { name: 'const.r', description: 'Carriage return character' },
  { name: 'const.t', description: 'Tab character' },
  { name: 'sys.arch', description: 'CPU architecture, e.g. x86_64' },
  { name: 'sys.bindir', description: 'CFEngine binaries directory' },
  { name: 'sys.cdate', description: 'Current date, agent-formatted string' },
  { name: 'sys.cf_edition', description: 'CFEngine edition (community or enterprise)' },
  { name: 'sys.cf_version', description: 'CFEngine version, e.g. 3.28.0' },
  { name: 'sys.cf_version_major', description: 'CFEngine major version number' },
  { name: 'sys.cf_version_minor', description: 'CFEngine minor version number' },
  { name: 'sys.cf_version_patch', description: 'CFEngine patch version number' },
  { name: 'sys.cf_version_release', description: 'CFEngine release number' },
  { name: 'sys.class', description: 'Kernel/OS class, e.g. linux, darwin' },
  { name: 'sys.cpus', description: 'Number of logical CPU cores' },
  { name: 'sys.crontab', description: 'Path to the system crontab' },
  { name: 'sys.date', description: 'Current date and time, human-readable' },
  { name: 'sys.default_policy_path', description: 'Path to the default policy entry point' },
  { name: 'sys.domain', description: 'DNS domain of this host' },
  { name: 'sys.exports', description: 'Path to the NFS exports file' },
  { name: 'sys.failsafe_policy_path', description: 'Path to the failsafe policy entry point' },
  { name: 'sys.flavor', description: 'Detailed OS flavor/version string' },
  { name: 'sys.flavour', description: 'Alias for sys.flavor' },
  { name: 'sys.fqhost', description: 'Fully qualified hostname' },
  { name: 'sys.fstab', description: 'Path to the filesystem table' },
  { name: 'sys.hardware_addresses', description: 'List of MAC addresses on this host' },
  { name: 'sys.hardware_flags', description: 'List of network interface flags' },
  { name: 'sys.host', description: 'Short hostname' },
  { name: 'sys.inet', description: 'IPv4 addresses discovered via /proc' },
  { name: 'sys.inet6', description: 'IPv6 addresses discovered via /proc' },
  { name: 'sys.inputdir', description: 'Policy inputs directory' },
  { name: 'sys.interface', description: 'Name of the primary network interface' },
  { name: 'sys.interfaces', description: 'List of network interface names' },
  { name: 'sys.ip_addresses', description: 'All IP addresses on this host' },
  { name: 'sys.ipv4', description: 'Primary IPv4 address' },
  { name: 'sys.keydir', description: 'Directory holding CFEngine trust keys' },
  { name: 'sys.libdir', description: 'Policy library directory' },
  { name: 'sys.local_libdir', description: 'Local (non-masterfiles) library directory' },
  { name: 'sys.logdir', description: 'CFEngine log directory' },
  { name: 'sys.long_arch', description: 'Full kernel/architecture identification string' },
  { name: 'sys.maildir', description: 'System mail spool directory' },
  { name: 'sys.masterdir', description: 'Masterfiles directory' },
  { name: 'sys.moduledir', description: 'CFEngine modules directory' },
  { name: 'sys.os', description: 'Operating system name, e.g. linux, darwin' },
  { name: 'sys.os_name_human', description: 'Human-readable OS name, e.g. macOS' },
  { name: 'sys.os_version_major', description: 'OS major version number' },
  { name: 'sys.os_version_minor', description: 'OS minor version number' },
  { name: 'sys.ostype', description: 'OS and architecture combined, e.g. linux_x86_64' },
  { name: 'sys.piddir', description: 'CFEngine PID file directory' },
  { name: 'sys.policy_entry_basename', description: 'Filename of the policy entry point' },
  { name: 'sys.policy_entry_dirname', description: 'Directory of the policy entry point' },
  { name: 'sys.policy_entry_filename', description: 'Full path of the policy entry point' },
  { name: 'sys.release', description: 'Kernel release string' },
  { name: 'sys.resolv', description: 'Path to the DNS resolver config' },
  { name: 'sys.statedir', description: 'CFEngine state directory' },
  { name: 'sys.sysday', description: 'Day number since epoch' },
  { name: 'sys.systime', description: 'Current Unix timestamp' },
  { name: 'sys.time_based_dom', description: 'Class-style day-of-month marker, e.g. Day15' },
  { name: 'sys.time_based_dow', description: 'Class-style day-of-week marker, e.g. Tuesday' },
  { name: 'sys.time_based_gmt_dom', description: 'GMT day-of-month marker' },
  { name: 'sys.time_based_gmt_dow', description: 'GMT day-of-week marker' },
  { name: 'sys.time_based_gmt_hr', description: 'GMT hour marker' },
  { name: 'sys.time_based_gmt_hr_2', description: 'GMT two-hour window marker' },
  { name: 'sys.time_based_gmt_hr_qoh', description: 'GMT quarter-of-hour marker' },
  { name: 'sys.time_based_gmt_lcycle', description: 'GMT five-minute lifecycle counter' },
  { name: 'sys.time_based_gmt_min', description: 'GMT minute marker' },
  { name: 'sys.time_based_gmt_min_span_5', description: 'GMT five-minute span marker' },
  { name: 'sys.time_based_gmt_month', description: 'GMT month marker' },
  { name: 'sys.time_based_gmt_pod', description: 'GMT part-of-day marker (Morning/Afternoon/…)' },
  { name: 'sys.time_based_gmt_qoh', description: 'GMT quarter-of-day marker' },
  { name: 'sys.time_based_gmt_yr', description: 'GMT year marker' },
  { name: 'sys.time_based_hr', description: 'Local hour marker' },
  { name: 'sys.time_based_hr_2', description: 'Local two-hour window marker' },
  { name: 'sys.time_based_hr_qoh', description: 'Local quarter-of-hour marker' },
  { name: 'sys.time_based_lcycle', description: 'Local five-minute lifecycle counter' },
  { name: 'sys.time_based_min', description: 'Local minute marker' },
  { name: 'sys.time_based_min_span_5', description: 'Local five-minute span marker' },
  { name: 'sys.time_based_month', description: 'Local month marker' },
  { name: 'sys.time_based_pod', description: 'Local part-of-day marker (Morning/Afternoon/…)' },
  { name: 'sys.time_based_qoh', description: 'Local quarter-of-day marker' },
  { name: 'sys.time_based_yr', description: 'Local year marker' },
  { name: 'sys.update_policy_path', description: 'Path to the update policy entry point' },
  { name: 'sys.uptime', description: 'System uptime in minutes' },
  { name: 'sys.uqhost', description: 'Unqualified hostname' },
  { name: 'sys.user_data', description: 'Details of the user running the agent (uid, home, shell…)' },
  { name: 'sys.version', description: 'Full kernel version string' },
  { name: 'sys.workdir', description: 'CFEngine working directory' }
];
