import { execFileSync } from 'child_process';
import { promises as fs } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';

import type { CreateProjectRequest, ProjectContent, ProjectStorage } from '../preload/api';
import { registerProjectHandlers } from './project';
import { type FileSpec, builderContent, debianEnvironment, mainFile, webFile } from './test/content';
import { type Handler, invoker, isTrustedFrame } from './test/ipc';
import { useVenvSidecar } from './test/sidecar';

const state = vi.hoisted(() => ({ handlers: new Map<string, Handler>(), userData: '' }));

vi.mock('electron', async importOriginal => {
  const original = await importOriginal<typeof import('./test/electron')>();
  return {
    ...original,
    app: { ...original.app, isPackaged: true, getPath: () => state.userData },
    ipcMain: { ...original.ipcMain, handle: (channel: string, handler: Handler) => void state.handlers.set(channel, handler) }
  };
});

type Json = Record<string, unknown>;
type Created = { masterfiles?: string | null; message?: string; ok: boolean; path?: string };
type Opened = { builder?: Json | null; cfbs?: Json; message?: string; ok: boolean; testEnvironments?: unknown[] | null };
type Saved = { masterfiles?: string | null; message?: string; ok: boolean };

const invoke = invoker(state.handlers);
let temp = '';

beforeAll(async () => {
  vi.stubEnv('GIT_CONFIG_GLOBAL', '/dev/null');
  vi.stubEnv('GIT_CONFIG_NOSYSTEM', '1');
  vi.stubEnv('GIT_ALLOW_PROTOCOL', 'file');
  registerProjectHandlers(isTrustedFrame);
});

beforeEach(async () => {
  temp = await fs.realpath(await fs.mkdtemp(join(tmpdir(), 'cfpb-project-it-')));
  state.userData = join(temp, 'user-data');
  await fs.mkdir(state.userData);
  await useVenvSidecar(join(temp, 'resources'));
});

afterEach(async () => {
  await fs.rm(temp, { recursive: true, force: true });
});

const git = (cwd: string, ...args: string[]) => execFileSync('git', args, { cwd, encoding: 'utf-8' }).trim();
const readJson = async (path: string): Promise<Json> => JSON.parse(await fs.readFile(path, 'utf-8'));
const exists = (path: string) =>
  fs.stat(path).then(
    () => true,
    () => false
  );

function create(content: ProjectContent, extra: Partial<CreateProjectRequest> = {}): Promise<Created> {
  const request: CreateProjectRequest = {
    ...content,
    parent: temp,
    folderName: 'web-demo',
    name: 'Web Demo',
    description: 'A demo web server',
    git: false,
    masterfiles: 'no',
    type: 'policy-set',
    ...extra
  };
  return invoke('project:create', request) as Promise<Created>;
}

const project = () => join(temp, 'web-demo');
const open = () => invoke('project:open', { path: project() }) as Promise<Opened>;
const save = (content: ProjectContent, storage: ProjectStorage = { type: 'policy-set', masterfiles: null }) =>
  invoke('project:save', { path: project(), ...content, storage }) as Promise<Saved>;
const buildNames = async () => ((await readJson(join(project(), 'cfbs.json'))).build as Json[]).map(entry => entry.name);

describe('project:create', () => {
  it('writes cfbs.json, the generated policy and the builder’s data', async () => {
    const content = builderContent([mainFile, webFile], [debianEnvironment]);
    expect(await create(content)).toEqual({ ok: true, masterfiles: null, path: project() });

    const cfbs = await readJson(join(project(), 'cfbs.json'));
    expect(cfbs).toMatchObject({ name: 'Web Demo', description: 'A demo web server', type: 'policy-set', git: false });
    expect(cfbs.build).toEqual(content.modules);

    const main = await fs.readFile(join(project(), 'main.cf'), 'utf-8');
    expect(main).toMatch(/^#{79}\n#\n# Says hello on every host\.\n#\n# Generated by CFEngine Policy Builder from "Main"\./);
    expect(main).toContain('bundle agent main');
    expect(main).toContain('"hello";');
    expect(await fs.readFile(join(project(), 'services', 'web.cf'), 'utf-8')).toContain('bundle agent web');

    expect(await readJson(join(project(), '.policy-builder', 'project.json'))).toEqual({
      ...content.project,
      tool_version: '0.0.0-test',
      generated: ['./main.cf', './services/web.cf']
    });
    expect(await readJson(join(project(), '.policy-builder', 'test-environments.json'))).toEqual({ environments: [debianEnvironment] });
  });

  it('refuses a folder that isn’t empty', async () => {
    await fs.mkdir(project());
    await fs.writeFile(join(project(), 'notes.txt'), 'mine');
    expect(await create(builderContent([mainFile]))).toMatchObject({ ok: false, message: expect.stringMatching(/^A folder named .web-demo. already exists/) });
    expect(await fs.readdir(project())).toEqual(['notes.txt']);
  });

  it('reports a compile error and leaves nothing behind', async () => {
    const content = builderContent([mainFile]);
    const files = (content.project as { files: Json[] }).files;
    files[0].blocks = [{ blockId: 'no-such-block', instanceId: 'x', label: 'x', params: {} }];
    const result = await create(content);
    expect(result.ok).toBe(false);
    expect(result.message).toContain('no-such-block');
    expect(await exists(project())).toBe(false);
  });

  it('makes one clean initial commit with git', async () => {
    expect((await create(builderContent([mainFile, webFile]), { git: true })).ok).toBe(true);
    expect(git(project(), 'log', '--format=%s')).toBe('Initialized a new CFEngine Build project');
    expect(git(project(), 'status', '--porcelain')).toBe('');
    expect(git(project(), 'ls-files')).toContain('.policy-builder/project.json');
  });

  it('commits the test environments too', async () => {
    expect((await create(builderContent([mainFile], [debianEnvironment]), { git: true })).ok).toBe(true);
    expect(git(project(), 'status', '--porcelain')).toBe('');
  });
});

describe('project:open', () => {
  it('returns what was created', async () => {
    const content = builderContent([mainFile, webFile], [debianEnvironment]);
    await create(content);
    const opened = await open();
    expect(opened.ok).toBe(true);
    expect(opened.builder).toEqual(await readJson(join(project(), '.policy-builder', 'project.json')));
    expect(opened.builder).toMatchObject({ files: content.project.files });
    expect(opened.cfbs).toEqual(await readJson(join(project(), 'cfbs.json')));
    expect(opened.testEnvironments).toEqual([debianEnvironment]);
  });

  it('opens a plain cfbs project without builder data', async () => {
    await fs.mkdir(project());
    await fs.writeFile(join(project(), 'cfbs.json'), JSON.stringify({ name: 'Plain', type: 'policy-set', build: [] }));
    expect(await open()).toMatchObject({ ok: true, builder: null, testEnvironments: null, cfbs: { name: 'Plain' } });
  });

  it('opens a module project', async () => {
    await create(builderContent([mainFile]), { type: 'module' });
    expect(await open()).toMatchObject({ ok: true, cfbs: { type: 'module' } });
  });
});

describe('project:save', () => {
  const renamed: FileSpec = { ...mainFile, name: 'Hello', bundle: 'hello', path: './hello.cf' };
  const other = { name: 'some-module', version: '1.0.0', added_by: 'cfbs add', steps: ['copy a.cf services/a.cf'] };

  beforeEach(async () => {
    expect((await create(builderContent([mainFile, webFile], [debianEnvironment]))).ok).toBe(true);
    // Another tool's entry, which saves must keep.
    const cfbs = await readJson(join(project(), 'cfbs.json'));
    await fs.writeFile(join(project(), 'cfbs.json'), JSON.stringify({ ...cfbs, build: [other, ...(cfbs.build as Json[])] }, null, 2));
  });

  it('removes the stale policy and updates cfbs.json', async () => {
    const content = builderContent([renamed], [debianEnvironment]);
    expect(await save(content)).toEqual({ ok: true, masterfiles: null });

    expect(await exists(join(project(), 'main.cf'))).toBe(false);
    expect(await exists(join(project(), 'services'))).toBe(false);
    expect(await fs.readFile(join(project(), 'hello.cf'), 'utf-8')).toContain('bundle agent hello');
    expect((await readJson(join(project(), 'cfbs.json'))).build).toEqual([other, ...content.modules]);
    expect(await readJson(join(project(), '.policy-builder', 'project.json'))).toMatchObject({ generated: ['./hello.cf'] });
  });

  it('keeps the test environments', async () => {
    expect((await save(builderContent([mainFile, webFile], [debianEnvironment]))).ok).toBe(true);
    expect((await open()).testEnvironments).toEqual([debianEnvironment]);
  });

  it('round-trips through open', async () => {
    const content = builderContent([renamed, webFile], [debianEnvironment]);
    await save(content);
    const opened = await open();
    expect(opened.builder).toMatchObject({ files: content.project.files, generated: ['./hello.cf', './services/web.cf'] });
    expect(opened.cfbs).toMatchObject({ name: 'Web Demo', build: [other, ...content.modules] });
    expect(opened.testEnvironments).toEqual([debianEnvironment]);
  });

  it('leaves the project alone when the policy doesn’t compile', async () => {
    const before = await fs.readFile(join(project(), 'main.cf'), 'utf-8');
    const content = builderContent([renamed]);
    (content.project as { files: Json[] }).files[0].blocks = [{ blockId: 'no-such-block', instanceId: 'x', label: 'x', params: {} }];
    const result = await save(content);
    expect(result.ok).toBe(false);
    expect(result.message).toContain('no-such-block');
    expect(await fs.readFile(join(project(), 'main.cf'), 'utf-8')).toBe(before);
    expect(await exists(join(project(), 'hello.cf'))).toBe(false);
    expect(await buildNames()).toEqual(['some-module', './main.cf', './services/']);
  });

  it('converts a policy set to a module and back', async () => {
    const content = builderContent([mainFile, webFile], [debianEnvironment]);
    expect(await save(content, { type: 'module', masterfiles: null })).toEqual({ ok: true, masterfiles: null });
    const module = await readJson(join(project(), 'cfbs.json'));
    expect(module).toMatchObject({ type: 'module', name: 'web-demo', build: [other] });
    expect(module.provides).toEqual({ 'web-demo': content.provided });

    // Back to a policy set without asking for masterfiles: no download.
    expect(await save(content)).toEqual({ ok: true, masterfiles: null });
    const policySet = await readJson(join(project(), 'cfbs.json'));
    expect(policySet).toMatchObject({ type: 'policy-set', name: 'Web Demo', build: [other, ...content.modules] });
    expect('provides' in policySet).toBe(false);
    expect(await readJson(join(project(), '.policy-builder', 'test-environments.json'))).toEqual({ environments: [debianEnvironment] });
  });
});

describe('module projects', () => {
  it('are created as cfbs modules, and saved as policy sets offline', async () => {
    const content = builderContent([mainFile, webFile]);
    expect(await create(content, { type: 'module' })).toEqual({ ok: true, masterfiles: null, path: project() });
    expect(await readJson(join(project(), 'cfbs.json'))).toEqual({
      name: 'web-demo',
      description: 'A demo web server',
      type: 'module',
      git: false,
      provides: { 'web-demo': content.provided }
    });

    expect(await save(content)).toEqual({ ok: true, masterfiles: null });
    expect(await buildNames()).toEqual(['./main.cf', './services/']);
  });
});
